### ISSUE TITLE
Weights not written for trained model

### ISSUE THREAD

**Issue by nspope** [kr-colab/diploSHIC#23]
Hi, thanks for developing this intuitive and useful tool.

With `python 3.69`, `tensorflow 1.14.0`, `keras 2.3.1`: weights from the trained model are not saved. This is fixed by changing `monitor = 'val_acc'` to `monitor = 'val_accuracy'` at:

https://github.com/kern-lab/diploSHIC/blob/7d55417af438e321c374dadc2f7e58f56107443e/diploSHIC.py#L250

For early stopping to work, the same change needs to made at:

https://github.com/kern-lab/diploSHIC/blob/7d55417af438e321c374dadc2f7e58f56107443e/diploSHIC.py#L243

Perhaps due to a recent change in keras or documentation thereof? (See https://github.com/tensorflow/tensorflow/issues/33163)

Nate

**Comment by andrewkern** [comment]
sorry just seeing this issue? is this still affecting things?

**Comment by andrewkern** [comment]
closing this issue as it seems stale. feel free to reopen
