### ISSUE TITLE
Encountering the problem of too few SNPs

### ISSUE THREAD

**Issue by jtxtina** [kr-colab/diploSHIC#27]
When I finished training with default totalPhysLen:1100000 and numSubWins:11, I tried to predict using a single sample from human vcf file. But during vcf->fvec process, it seems that for human chromosomes, SNPs are just too few such that there are few "good" subwindows to write out statistics, which results in empty diploid.fvec file.
Any suggestion to improve this?

**Comment by jtxtina** [comment]
And when I trained a numSubWins=5 version model, when "fvecvcf', there are always 50 statistics value being 0.2. 
E.g. 21	45450001	45550000	45300001-45800000	0.04347795840815315	0.04347795840815315	0.34783062387770275	0.1739118336326126	0.39130162567337834	0.04347795840815315	0.04347795840815315	0.34783062387770275	0.1739118336326126	0.39130162567337834	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2

**Comment by andrewkern** [comment]
> > do you mean a single human genome here?
> 
> Yes. It's a vcf file containing a single human's gene (from chr1 - chrx/y, etc.).

diploSHIC isn't meant to be run on a single genome-- it calculates summaries from population level samples, for instance n=10+ genomes

**Comment by jtxtina** [comment]
> > > do you mean a single human genome here?
> > 
> > 
> > Yes. It's a vcf file containing a single human's gene (from chr1 - chrx/y, etc.).
> 
> diploSHIC isn't meant to be run on a single genome-- it calculates summaries from population level samples, for instance n=10+ genomes
I see. And how about numSubWins? What are your standards for choosing it for value other than 11?

**Comment by jtxtina** [comment]
Ok I used multiple samples and it worked perfectly. Thank you
