### ISSUE TITLE
testing file input size not equal to preds output size

### ISSUE THREAD

**Issue by stsmall** [kr-colab/diploSHIC#36]
Hi @andrewkern,
I am using an fvec of 500 sims (500 lines + header) for testing classification with a previously constructed model. When I run  'predict' with the option --simData the resulting file has fewer than 500 lines. E.g., 323. I also checked this for the empirical fvecs and the input and output files are also not the same size. Am I missing something here? Like a cutoff option for reporting?
thanks,
@stsmall 

Edit: The output from predict prints '500 predictions complete', but only 322 are in the output file
Edit2: The length of preds and predictions (in the diploSHIC.py) are both 500.
Edit3: When I drop into the code (ipdb) right after preds to check the length, then 'c' to continue ... the resulting file is 500 lines! BUT once I remove the breakpoint and run it back to <500 ... lol, I think I am losing my mind

**Comment by stsmall** [comment]
It seems the culprit is on Ln 319, there is not an () on outputFile.close. If I change it to outputFile.close() ... it works as expected.

**Comment by andrewkern** [comment]
well that's a crappy bug. @stsmall do you want to submit a little PR so that you can get credit for this bug fix?

**Comment by stsmall** [comment]
No thanks. Glad to have helped out.
