### ISSUE TITLE
Installation in Windows 

### ISSUE THREAD

**Issue by vkhanna7** [kr-colab/diploSHIC#43]
I have anaconda installed in Windows. Is it possible to install the software in windows? I am running into an error when I try to do it 
"note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diploSHIC
Failed to build diploSHIC
ERROR: Could not build wheels for diploSHIC, which is required to install pyproject.toml-based projects"

Would really appreciate it if anyone can help.
Thanks

**Comment by andrewkern** [comment]
hi @vkhanna7 -- are you running Windows 11? If so, I think the best way to do this would be to use `wsl`. If you open a `wsl` session and then use conda from within the linux sublayer you _should_ be all set... at least I think so?
