### ISSUE TITLE
Error installing on Condor 

### ISSUE THREAD

**Issue by vkhanna7** [kr-colab/diploSHIC#44]
I am trying to install it and keep getting  /var/lib/condor/execute/slot1/dir_30386/python/bin/pip: /var/lib/condor/execute/slot1/dir_18429/python/bin/python3.9: bad interpreter: No such file or directory
I am trying to clone and then install.
Any help would be appreciated.

**Comment by andrewkern** [comment]
this has to do with your python installation and not diploSHIC
