### ISSUE TITLE
"-Pa" parameters question

### ISSUE THREAD

**Issue by pengyan19** [kr-colab/diploSHIC#48]
Hi;
    when i used your software discoal, i didn't know the "-Pa" parameters. whether we need to change the selection coefficient to 4N0? For example, when the selection coefficient were 0.5, the "-Pa" parameters were shows that 4N0*s (selection coefficient)?

**Comment by andrewkern** [comment]
sorry this is an issue about `discoal`. could you please open this issue on that repo?
