### ISSUE TITLE
ValueError  cannot reshape array of size 150000 into shape (1000,13,11)

### ISSUE THREAD

**Issue by vkhanna7** [kr-colab/diploSHIC#49]
for f in dip_data/*.out; do python3 ./packages/bin/diploSHIC fvecSim haploid $f $f.haploid.fvec --totalPhysLen 1000000 --numSubWins 10; done
mkdir sim3_rawFVFiles && mv dip_data/*.fvec sim3_rawFVFiles/
mkdir sim3_trainingSets
python3 ./packages/bin/diploSHIC makeTrainingSets sim3_rawFVFiles/neutral.out.haploid.fvec sim3_rawFVFiles/soft \
sim3_rawFVFiles/hard 5 0,1,2,3,4,6,7,8,9,10 sim3_trainingSets/

python3 ./packages/bin/diploSHIC train sim3_trainingSets/ sim3_trainingSets/ bfsModel

 The last step gives ValueError. Any suggestions or recommendations?

**Comment by andrewkern** [comment]
you have a mismatch between the number of subwindows you calculated stats on and the number of subwindows you are telling makeTrainingSets to use, it looks like.
